// Generated by CoffeeScript 1.10.0
(function() {
  var exports;

  exports = this;

  exports.Digit = (function() {
    function Digit() {}

    Digit.isInteger = function(number) {
      number = Number(number);
      return Math.floor(number) === number;
    };

    Digit.isFloat = function(number) {
      return !this.isInteger(number);
    };

    Digit.removeSymbol = function(numberString) {
      return numberString.replace(/[-\+\.]/g, '');
    };

    Digit.get = function(number) {
      var digit, numberString;
      numberString = number.toString(10);
      numberString = this.removeSymbol(numberString);
      return digit = numberString.length;
    };

    Digit.getIntegerPart = function(number) {
      var numberString;
      numberString = Math.floor(number).toString();
      numberString = this.removeSymbol(numberString);
      return numberString.length;
    };

    Digit.getDecimalPart = function(number) {
      var numberString;
      if (this.isInteger(number)) {
        return 0;
      }
      numberString = number.toString();
      numberString = numberString.match(/(?=.)\d+$/)[0];
      return numberString.length;
    };

    Digit.alignIntegerPart = function(number, padding, maxDigit) {
      var diffIntDigit, i, intDigit, j, numberString, ref;
      intDigit = this.getIntegerPart(number);
      diffIntDigit = maxDigit - intDigit;
      if (diffIntDigit < 0) {
        throw new Error("Number is over maxDigit");
      }
      numberString = number.toString();
      if (number < 0) {
        numberString = numberString.replace('-', '');
      }
      for (i = j = 0, ref = diffIntDigit; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        numberString = padding + numberString;
      }
      if (number < 0) {
        numberString = '-' + numberString;
      }
      return numberString;
    };

    Digit.align = function(number, intPadding, maxIntDigit, maxDecimalDigit, decimalPadding) {
      var base, diffFloatDigit, diffIntDigit, floatDigit, i, intDigit, j, k, numberString, ref, ref1;
      if (maxDecimalDigit == null) {
        maxDecimalDigit = 0;
      }
      if (decimalPadding == null) {
        decimalPadding = 0;
      }
      numberString = number.toString();
      intDigit = this.getIntegerPart(number);
      diffIntDigit = maxIntDigit - intDigit;
      if (number < 0) {
        numberString = numberString.replace('-', '');
      }
      for (i = j = 0, ref = diffIntDigit; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        numberString = intPadding + numberString;
      }
      if (number < 0) {
        numberString = '-' + numberString;
      }
      if (this.isInteger(number) && maxDecimalDigit === 0) {
        return numberString;
      }
      if (this.getDecimalPart(number) === 0) {
        numberString += '.';
      }
      floatDigit = this.getDecimalPart(number);
      diffFloatDigit = maxDecimalDigit - floatDigit;
      if (diffFloatDigit <= -1) {
        base = 10 ^ Math.abs(diffFloatDigit);
        numberString *= base;
        Math.round(numberString);
        return numberString /= base;
      } else if (diffFloatDigit >= 1) {
        for (i = k = 0, ref1 = diffFloatDigit; 0 <= ref1 ? k < ref1 : k > ref1; i = 0 <= ref1 ? ++k : --k) {
          numberString += decimalPadding;
        }
        return numberString;
      } else {
        return numberString;
      }
    };

    return Digit;

  })();

}).call(this);
